apiVersion: v1
kind: Service
metadata:
  name: demo-service-008
  labels:
    app.kubernetes.io/name: demo-service-008
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: demo-service-008
  ports:
    - name: http
      port: 80
      targetPort: http
