apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-service-008
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MichaelF21/demo-service-008.git
    targetRevision: main
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-service-008
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
